### ISSUE TITLE
Inconsistency of miniworkshop/workshop and longworkshop

### ISSUE THREAD

**Issue by FelixPetriconi** [ACCUConf/Submission_Web_Application#81] opened 2018-09-23 10:05 UTC
This leads to an application error

**Comment by russel** [comment] 2018-09-23 10:51
Curses. I thought I had removed all the miniworkshop, replaced by workshop, and added longworkshop for all the workshops. I now see I failed to amend the JavaScript file. This will definitely be the cause of the problem.

**Comment by russel** [comment] 2018-09-23 10:52
@FelixPetriconi  I assigned this to you as per the email, but I can pick this one up later today if you want. The JavaScript code isn't as well tested as the Python code. :-(

**Closed** 2018-09-23 15:43 UTC
Labels: bug
